Repository Icinga/icinga-powershell-plugins, pull requests merged in 2020-11, with the labels that each got.

#88 Disable OnSameLine & don't check space before open brace
  PSScriptAnalyzerSettings.psd1
Labels: bug

#85 Feature: Add support to ignore empty checks on UsedPartitionSpace plugin and ignore Unknowns
  doc/31-Changelog.md
  doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Labels: enhancement

#74 Feature/Add avg. disk queue length PerfCounter
  doc/31-Changelog.md
  doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
  plugins/Invoke-IcingaCheckDiskHealth.psm1
Labels: enhancement

#89 Doc: Adds documentation for plugin permission requirements
  doc/plugins/01-Invoke-IcingaCheckBiosSerial.md
  doc/plugins/02-Invoke-IcingaCheckCertificate.md
  doc/plugins/03-Invoke-IcingaCheckCheckSum.md
  doc/plugins/04-Invoke-IcingaCheckCPU.md
  doc/plugins/07-Invoke-IcingaCheckFirewall.md
  doc/plugins/08-Invoke-IcingaCheckICMP.md
  doc/plugins/09-Invoke-IcingaCheckMemory.md
  doc/plugins/10-Invoke-IcingaCheckNLA.md
  doc/plugins/11-Invoke-IcingaCheckPerfcounter.md
  doc/plugins/12-Invoke-IcingaCheckProcessCount.md
  doc/plugins/14-Invoke-IcingaCheckUpdates.md
  doc/plugins/15-Invoke-IcingaCheckUptime.md
  doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
  doc/plugins/17-Invoke-IcingaCheckUsers.md
  doc/plugins/18-Invoke-IcingaCheckTimeSync.md
  doc/plugins/19-Invoke-IcingaCheckScheduledTask.md
  doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
  plugins/Invoke-IcingaCheckBiosSerial.psm1
  plugins/Invoke-IcingaCheckCPU.psm1
  plugins/Invoke-IcingaCheckDiskHealth.psm1
  plugins/Invoke-IcingaCheckEventlog.psm1
  plugins/Invoke-IcingaCheckMemory.psm1
  plugins/Invoke-IcingaCheckPerfcounter.psm1
  plugins/Invoke-IcingaCheckProcessCount.psm1
  plugins/Invoke-IcingaCheckUpdates.psm1
  plugins/Invoke-IcingaCheckUptime.psm1
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
  plugins/Invoke-IcingaCheckUsers.psm1
Labels: documentation

#43 Check availability and state of Network devices
  doc/10-Icinga-Plugins.md
  doc/plugins/21-Invoke-IcingaCheckNetworkInterface.md
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
  provider/enums/Icinga_ProviderEnums.psm1
  provider/network/Get-IcingaInterfaceAverageBandWidthUsage.psm1
  provider/network/Get-IcingaNetworkDeviceInfo.psm1
  provider/network/Get-IcingaNetworkInterfaceTeamInfo.psm1
  provider/network/Get-IcingaNetworkInterfaceUnits.psm1
  provider/network/Get-IcingaNetworkSpeedChecks.psm1
  provider/network/Join-icingaNetworkDeviceDataPerfCounter.psm1
Labels: enhancement

#98 Fix: Invoke-IcingaCheckScheduledTask returns invalid perf data output
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckScheduledTask.psm1
  provider/enums/Icinga_ProviderEnums.psm1
Labels: bug

#91 Feature: Adds support to ignore read only/offline disks on Invoke-IcingaCheckDiskHealth
  doc/31-Changelog.md
  doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
  plugins/Invoke-IcingaCheckDiskHealth.psm1
Labels: enhancement

#102 Fix: Invoke-IcingaCheckNetworkInterface arguments too long for Icinga Director
  doc/31-Changelog.md
  doc/plugins/19-Invoke-IcingaCheckScheduledTask.md
  doc/plugins/21-Invoke-IcingaCheckNetworkInterface.md
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
Labels: bug

#103 Fix: Invoke-IcingaCheckNetworkInterface plugin args are too long
  doc/31-Changelog.md
  doc/plugins/21-Invoke-IcingaCheckNetworkInterface.md
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
Labels: bug

#105 Docs: Adds link to installation docs on upgrading docs
  doc/30-Upgrading-Plugins.md
Labels: documentation

#106 Doc: Updates changelog for new plugins
  doc/31-Changelog.md
Labels: documentation

#104 Feature: Add pre-compiled plugin configuration
  config/director/Invoke-IcingaCheckBiosSerial.json
  config/director/Invoke-IcingaCheckCPU.json
  config/director/Invoke-IcingaCheckCertificate.json
  config/director/Invoke-IcingaCheckCheckSum.json
  config/director/Invoke-IcingaCheckDirectory.json
  config/director/Invoke-IcingaCheckDiskHealth.json
  config/director/Invoke-IcingaCheckEventlog.json
  config/director/Invoke-IcingaCheckFirewall.json
  config/director/Invoke-IcingaCheckICMP.json
  config/director/Invoke-IcingaCheckMemory.json
  config/director/Invoke-IcingaCheckNLA.json
  config/director/Invoke-IcingaCheckNetworkInterface.json
  config/director/Invoke-IcingaCheckPerfcounter.json
  config/director/Invoke-IcingaCheckProcessCount.json
  config/director/Invoke-IcingaCheckScheduledTask.json
  config/director/Invoke-IcingaCheckService.json
  config/director/Invoke-IcingaCheckTimeSync.json
  config/director/Invoke-IcingaCheckUpdates.json
  config/director/Invoke-IcingaCheckUptime.json
  config/director/Invoke-IcingaCheckUsedPartitionSpace.json
  config/director/Invoke-IcingaCheckUsers.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckBiosSerial.conf
  config/icinga/Invoke-IcingaCheckCPU.conf
  config/icinga/Invoke-IcingaCheckCertificate.conf
  config/icinga/Invoke-IcingaCheckCheckSum.conf
  config/icinga/Invoke-IcingaCheckDirectory.conf
  config/icinga/Invoke-IcingaCheckDiskHealth.conf
  config/icinga/Invoke-IcingaCheckEventlog.conf
  config/icinga/Invoke-IcingaCheckFirewall.conf
  config/icinga/Invoke-IcingaCheckICMP.conf
  config/icinga/Invoke-IcingaCheckMemory.conf
  config/icinga/Invoke-IcingaCheckNLA.conf
  config/icinga/Invoke-IcingaCheckNetworkInterface.conf
  config/icinga/Invoke-IcingaCheckPerfcounter.conf
  config/icinga/Invoke-IcingaCheckProcessCount.conf
  config/icinga/Invoke-IcingaCheckScheduledTask.conf
  config/icinga/Invoke-IcingaCheckService.conf
  config/icinga/Invoke-IcingaCheckTimeSync.conf
  config/icinga/Invoke-IcingaCheckUpdates.conf
  config/icinga/Invoke-IcingaCheckUptime.conf
  config/icinga/Invoke-IcingaCheckUsedPartitionSpace.conf
  config/icinga/Invoke-IcingaCheckUsers.conf
  config/icinga/Plugins_Bundle.conf
  config/icinga/PowerShell_Base.conf
  doc/31-Changelog.md
Labels: enhancement

#58 Get Availability, State and Utilization of Storage Pools
  config/director/Invoke-IcingaCheckStoragePool.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckStoragePool.conf
  config/icinga/Plugins_Bundle.conf
  doc/10-Icinga-Plugins.md
  doc/plugins/21-Invoke-IcingaCheckStoragePool.md
  plugins/Invoke-IcingaCheckStoragePool.psm1
  provider/enums/Icinga_ProviderEnums.psm1
  provider/storage/Get-IcingaConvertToGigaByte.psm1
  provider/storage/Get-IcingaStoragePoolInfo.psm1
Labels: enhancement

#61 Adds exception handling for win updates permission
  doc/31-Changelog.md
  provider/updates/Get-IcingaUpdatesInstalled.psm1
  provider/updates/Get-IcingaUpdatesPending.psm1
Labels: enhancement

#108 Docs: Updates upgrading/changelog docs
  doc/30-Upgrading-Plugins.md
  doc/31-Changelog.md
Labels: documentation

#101 Feature: Changed Invoke-IcingaCheckScheduledTask to support multi States
  doc/30-Upgrading-Plugins.md
  doc/31-Changelog.md
Labels: enhancement

#109 Fix: Adds exception handling for checksum plugin
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckCheckSum.psm1
Labels: bug

#110 Fix: Eventlog throwing unknown on valid arguments
  doc/31-Changelog.md
  provider/eventlog/Get-IcingaEventLog.psm1
Labels: bug

#111 Docs: Fix broken link in upgrading docs
  doc/30-Upgrading-Plugins.md
Labels: documentation

#112 Feature: Updates version to 1.4.0
  doc/30-Upgrading-Plugins.md
  doc/31-Changelog.md
  icinga-powershell-plugins.psd1
Labels: enhancement
