Repository Icinga/icinga-powershell-plugins, pull requests merged in 2020-10, with the labels that each got.

#76 Doc: Improve documentation for Invoke-IcingaCheckDirectory
  doc/plugins/05-Invoke-IcingaCheckDirectory.md
  plugins/Invoke-IcingaCheckDirectory.psm1
Labels: documentation

#80 Fix: IcingaCheckService with wildcard includes service name with wildcard in checkresult
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckService.psm1
Labels: bug

#82 Doc: Add required permissions for EventLog check
  doc/plugins/06-Invoke-IcingaCheckEventlog.md
  plugins/Invoke-IcingaCheckEventlog.psm1
Labels: documentation

#84 Fix: Throw unknown in case partition data cant be read
  doc/31-Changelog.md
  doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
  provider/disks/Icinga_ProviderDisks.psm1
Labels: bug, enhancement

#86 Fix: Get-IcingaCPUCount returns wrong count on empty arguments
  doc/31-Changelog.md
  provider/cpu/Icinga_ProviderCpu.psm1
Labels: bug

#77 Bugfix: Fix wrong behaviour for CheckEventLog and increase Performance
  doc/31-Changelog.md
  doc/plugins/06-Invoke-IcingaCheckEventlog.md
  plugins/Invoke-IcingaCheckEventlog.psm1
  provider/eventlog/Get-IcingaEventLog.psm1
Labels: bug, enhancement

#81 Fix: Improves documentation and output for Invoke-IcingaCheckService
  doc/31-Changelog.md
  doc/plugins/13-Invoke-IcingaCheckService.md
  plugins/Invoke-IcingaCheckService.psm1
  provider/services/Add-IcingaServiceSummary.psm1
  provider/services/New-IcingaWindowsServiceCheckObject.psm1
Labels: enhancement

#68 Bugfix/throw unhandled error when calling join func with null arg
  doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
  plugins/Invoke-IcingaCheckDiskHealth.psm1
  provider/disks/Get-IcingaPhysicalDiskInfo.psm1
Labels: bug
