Repository Icinga/icinga-powershell-plugins, pull requests merged in 2021-06, with the labels that each got.

#185 Fix: Network interface percent for teams not working
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
  provider/network/Get-IcingaNetworkInterfaceTeamInfo.psm1
Labels: bug

#186 Fix: Exception on plugin import on deleted plugin folder
  doc/31-Changelog.md
  icinga-powershell-plugins.psm1
Labels: bug

#172 Feature: Implement check MPIO plugin
  config/director/Invoke-IcingaCheckMPIO.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckMPIO.conf
  config/icinga/Plugins_Bundle.conf
  doc/10-Icinga-Plugins.md
  doc/31-Changelog.md
  doc/plugins/26-Invoke-IcingaCheckMPIO.md
  icinga-powershell-plugins.psd1
  plugins/Invoke-IcingaCheckMPIO.psm1
  provider/mpio/Get-IcingaMPIOData.psm1
  provider/mpio/Test-IcingaMPIOInstalled.psm1
Labels: enhancement

#194 Docs: Used partition space argument description
  config/director/Invoke-IcingaCheckUsedPartitionSpace.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckUsedPartitionSpace.conf
  config/icinga/Plugins_Bundle.conf
  doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Labels: documentation

#197 Fix: Icinga Plugin configuration
  config/director/Invoke-IcingaCheckBiosSerial.json
  config/director/Invoke-IcingaCheckCPU.json
  config/director/Invoke-IcingaCheckCertificate.json
  config/director/Invoke-IcingaCheckCheckSum.json
  config/director/Invoke-IcingaCheckDirectory.json
  config/director/Invoke-IcingaCheckDiskHealth.json
  config/director/Invoke-IcingaCheckEventlog.json
  config/director/Invoke-IcingaCheckFirewall.json
  config/director/Invoke-IcingaCheckHTTPStatus.json
  config/director/Invoke-IcingaCheckICMP.json
  config/director/Invoke-IcingaCheckMPIO.json
  config/director/Invoke-IcingaCheckMemory.json
  config/director/Invoke-IcingaCheckNLA.json
  config/director/Invoke-IcingaCheckNetworkInterface.json
  config/director/Invoke-IcingaCheckPerfcounter.json
  config/director/Invoke-IcingaCheckProcessCount.json
  config/director/Invoke-IcingaCheckScheduledTask.json
  config/director/Invoke-IcingaCheckService.json
  config/director/Invoke-IcingaCheckStoragePool.json
  config/director/Invoke-IcingaCheckTCP.json
  config/director/Invoke-IcingaCheckTimeSync.json
  config/director/Invoke-IcingaCheckUNCPath.json
  config/director/Invoke-IcingaCheckUpdates.json
  config/director/Invoke-IcingaCheckUptime.json
  config/director/Invoke-IcingaCheckUsedPartitionSpace.json
  config/director/Invoke-IcingaCheckUsers.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckBiosSerial.conf
  config/icinga/Invoke-IcingaCheckCPU.conf
  config/icinga/Invoke-IcingaCheckCertificate.conf
  config/icinga/Invoke-IcingaCheckCheckSum.conf
  config/icinga/Invoke-IcingaCheckDirectory.conf
  config/icinga/Invoke-IcingaCheckDiskHealth.conf
  config/icinga/Invoke-IcingaCheckEventlog.conf
  config/icinga/Invoke-IcingaCheckFirewall.conf
  config/icinga/Invoke-IcingaCheckHTTPStatus.conf
  config/icinga/Invoke-IcingaCheckICMP.conf
  config/icinga/Invoke-IcingaCheckMPIO.conf
  config/icinga/Invoke-IcingaCheckMemory.conf
  config/icinga/Invoke-IcingaCheckNLA.conf
  config/icinga/Invoke-IcingaCheckNetworkInterface.conf
  config/icinga/Invoke-IcingaCheckPerfcounter.conf
  config/icinga/Invoke-IcingaCheckProcessCount.conf
  config/icinga/Invoke-IcingaCheckScheduledTask.conf
  config/icinga/Invoke-IcingaCheckService.conf
  config/icinga/Invoke-IcingaCheckStoragePool.conf
  config/icinga/Invoke-IcingaCheckTCP.conf
  config/icinga/Invoke-IcingaCheckTimeSync.conf
  config/icinga/Invoke-IcingaCheckUNCPath.conf
  config/icinga/Invoke-IcingaCheckUpdates.conf
  config/icinga/Invoke-IcingaCheckUptime.conf
  config/icinga/Invoke-IcingaCheckUsedPartitionSpace.conf
  config/icinga/Invoke-IcingaCheckUsers.conf
  config/icinga/Plugins_Bundle.conf
Labels: bug

#198 Docs: Fix for used partition space include/exclude description
  config/director/Invoke-IcingaCheckUsedPartitionSpace.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckUsedPartitionSpace.conf
  config/icinga/Plugins_Bundle.conf
  doc/plugins/16-Invoke-IcingaCheckUsedPartitionSpace.md
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Labels: documentation

#202 Fix: Slahes for Invoke-IcingaCheckUsedPartitionSpace are removed again
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Labels: enhancement
