Repository Icinga/icinga-powershell-plugins, pull requests merged in 2022-08, with the labels that each got.

#307 Feature: Adds include/exclude filter for perfcounter plugin
  compiled/icinga-powershell-plugins.ifw_compilation.psm1
  config/director/Invoke-IcingaCheckPerfcounter.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckPerfcounter.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/11-Invoke-IcingaCheckPerfcounter.md
  plugins/Invoke-IcingaCheckPerfcounter.psm1
Labels: enhancement, cla/signed

#313 Feature: Adds support for thumbprint exclude for certificate plugin
  config/director/Invoke-IcingaCheckCertificate.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckCertificate.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/02-Invoke-IcingaCheckCertificate.md
  plugins/Invoke-IcingaCheckCertificate.psm1
  provider/certificate/Test-IcingaCertificateExcludePattern.psm1
Labels: enhancement, cla/signed

#303 Features: Adds new performance data handling
  config/grafana/dashboards/windows-base.json
  config/grafana/dashboards/windows-disks.json
  config/grafana/dashboards/windows-load.json
  config/grafana/dashboards/windows-memory.json
  config/grafana/dashboards/windows-network.json
  config/grafana/dashboards/windows-services.json
  config/grafana/dashboards/windows-updates.json
  config/grafana/icingaweb2-grafana/graphs.ini
  plugins/Invoke-IcingaCheckCPU.psm1
  plugins/Invoke-IcingaCheckDirectory.psm1
  plugins/Invoke-IcingaCheckDiskHealth.psm1
  plugins/Invoke-IcingaCheckEventlog.psm1
  plugins/Invoke-IcingaCheckFirewall.psm1
  plugins/Invoke-IcingaCheckHTTPStatus.psm1
  plugins/Invoke-IcingaCheckICMP.psm1
  plugins/Invoke-IcingaCheckMPIO.psm1
  plugins/Invoke-IcingaCheckMemory.psm1
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
  plugins/Invoke-IcingaCheckPerfcounter.psm1
  plugins/Invoke-IcingaCheckProcess.psm1
  plugins/Invoke-IcingaCheckProcessCount.psm1
  plugins/Invoke-IcingaCheckScheduledTask.psm1
  plugins/Invoke-IcingaCheckService.psm1
  plugins/Invoke-IcingaCheckStoragePool.psm1
  plugins/Invoke-IcingaCheckTCP.psm1
  plugins/Invoke-IcingaCheckTimeSync.psm1
  plugins/Invoke-IcingaCheckUNCPath.psm1
  plugins/Invoke-IcingaCheckUpdates.psm1
  plugins/Invoke-IcingaCheckUptime.psm1
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
  plugins/Invoke-IcingaCheckUsers.psm1
  provider/network/Get-IcingaNetworkSpeedChecks.psm1
  provider/private/services/New-IcingaWindowsServiceCheckObject.psm1
Labels: enhancement, cla/signed

#318 Feature: Updates config for IfW v1.10.0
  config/director/Invoke-IcingaCheckBiosSerial.json
  config/director/Invoke-IcingaCheckCPU.json
  config/director/Invoke-IcingaCheckCertificate.json
  config/director/Invoke-IcingaCheckCheckSum.json
  config/director/Invoke-IcingaCheckDirectory.json
  config/director/Invoke-IcingaCheckDiskHealth.json
  config/director/Invoke-IcingaCheckEventlog.json
  config/director/Invoke-IcingaCheckFirewall.json
  config/director/Invoke-IcingaCheckHTTPStatus.json
  config/director/Invoke-IcingaCheckICMP.json
  config/director/Invoke-IcingaCheckMPIO.json
  config/director/Invoke-IcingaCheckMemory.json
  config/director/Invoke-IcingaCheckNLA.json
  config/director/Invoke-IcingaCheckNetworkInterface.json
  config/director/Invoke-IcingaCheckPartitionSpace.json
  config/director/Invoke-IcingaCheckPerfcounter.json
  config/director/Invoke-IcingaCheckProcess.json
  config/director/Invoke-IcingaCheckProcessCount.json
  config/director/Invoke-IcingaCheckScheduledTask.json
  config/director/Invoke-IcingaCheckService.json
  config/director/Invoke-IcingaCheckStoragePool.json
  config/director/Invoke-IcingaCheckTCP.json
  config/director/Invoke-IcingaCheckTimeSync.json
  config/director/Invoke-IcingaCheckUNCPath.json
  config/director/Invoke-IcingaCheckUpdates.json
  config/director/Invoke-IcingaCheckUptime.json
  config/director/Invoke-IcingaCheckUsedPartitionSpace.json
  config/director/Invoke-IcingaCheckUsers.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckBiosSerial.conf
  config/icinga/Invoke-IcingaCheckCPU.conf
  config/icinga/Invoke-IcingaCheckCertificate.conf
  config/icinga/Invoke-IcingaCheckCheckSum.conf
  config/icinga/Invoke-IcingaCheckDirectory.conf
  config/icinga/Invoke-IcingaCheckDiskHealth.conf
  config/icinga/Invoke-IcingaCheckEventlog.conf
  config/icinga/Invoke-IcingaCheckFirewall.conf
  config/icinga/Invoke-IcingaCheckHTTPStatus.conf
  config/icinga/Invoke-IcingaCheckICMP.conf
  config/icinga/Invoke-IcingaCheckMPIO.conf
  config/icinga/Invoke-IcingaCheckMemory.conf
  config/icinga/Invoke-IcingaCheckNLA.conf
  config/icinga/Invoke-IcingaCheckNetworkInterface.conf
  config/icinga/Invoke-IcingaCheckPartitionSpace.conf
  config/icinga/Invoke-IcingaCheckPerfcounter.conf
  config/icinga/Invoke-IcingaCheckProcess.conf
  config/icinga/Invoke-IcingaCheckProcessCount.conf
  config/icinga/Invoke-IcingaCheckScheduledTask.conf
  config/icinga/Invoke-IcingaCheckService.conf
  config/icinga/Invoke-IcingaCheckStoragePool.conf
  config/icinga/Invoke-IcingaCheckTCP.conf
  config/icinga/Invoke-IcingaCheckTimeSync.conf
  config/icinga/Invoke-IcingaCheckUNCPath.conf
  config/icinga/Invoke-IcingaCheckUpdates.conf
  config/icinga/Invoke-IcingaCheckUptime.conf
  config/icinga/Invoke-IcingaCheckUsedPartitionSpace.conf
  config/icinga/Invoke-IcingaCheckUsers.conf
  config/icinga/Plugins_Bundle.conf
  doc/10-Icinga-Plugins.md
  doc/plugins/27-Invoke-IcingaCheckProcess.md
Labels: enhancement, cla/signed

#300 Feature: Adds flag to HTTP check to turn UNKNOWN to CRITICAL on connection errors
  config/director/Invoke-IcingaCheckHTTPStatus.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckHTTPStatus.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/25-Invoke-IcingaCheckHTTPStatus.md
  plugins/Invoke-IcingaCheckHTTPStatus.psm1
  provider/http/Get-IcingaCheckHTTPQuery.psm1
Labels: cla/signed

#249 Fix: Disk health plugin metadata
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckDiskHealth.psm1
  provider/disks/Get-IcingaPhysicalDiskInfo.psm1
  provider/disks/Icinga_ProviderDisks.psm1
  provider/enums/Icinga_ProviderEnums.psm1
Labels: bug, cla/signed

#279 Feature: Adds option to check if reboot is pending on update plugin
  config/director/Invoke-IcingaCheckUpdates.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckUpdates.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/14-Invoke-IcingaCheckUpdates.md
  plugins/Invoke-IcingaCheckUpdates.psm1
  provider/private/updates/Get-IcingaWindowsUpdatesPending.psm1
Labels: enhancement, cla/signed

#317 Feature: Adds support to include/exclude network device by name/connection
  config/director/Invoke-IcingaCheckNetworkInterface.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckNetworkInterface.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/21-Invoke-IcingaCheckNetworkInterface.md
  plugins/Invoke-IcingaCheckNetworkInterface.psm1
  provider/network/Join-icingaNetworkDeviceDataPerfCounter.psm1
Labels: enhancement, cla/signed

#319 Fix: Removes performance metric for CheckSum plugin
  doc/31-Changelog.md
  plugins/Invoke-IcingaCheckCheckSum.psm1
Labels: bug, cla/signed

#284 added param to ignore certain task-exit-codes for Invoke-IcingaCheckScheduledTask
  config/director/Invoke-IcingaCheckScheduledTask.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckScheduledTask.conf
  config/icinga/Plugins_Bundle.conf
  doc/31-Changelog.md
  doc/plugins/19-Invoke-IcingaCheckScheduledTask.md
  doc/plugins/20-Invoke-IcingaCheckDiskHealth.md
  plugins/Invoke-IcingaCheckScheduledTask.psm1
Labels: enhancement, cla/signed

#195 small addition to 16-Invoke-IcingaCheckUsedPartitionSpace.md for usag…
  plugins/Invoke-IcingaCheckUsedPartitionSpace.psm1
Labels: documentation

#290 Add plugin to check JSON-Response
  config/director/Invoke-IcingaCheckHttpJsonResponse.json
  config/director/Plugins_Bundle.json
  config/icinga/Invoke-IcingaCheckHttpJsonResponse.conf
  config/icinga/Plugins_Bundle.conf
  doc/10-Icinga-Plugins.md
  doc/31-Changelog.md
  doc/plugins/14-Invoke-IcingaCheckUpdates.md
  doc/plugins/28-Invoke-IcingaCheckHttpJsonResponse.md
  icinga-powershell-plugins.psd1
  plugins/Invoke-IcingaCheckHttpJsonResponse.psm1
  provider/httpJson/Get-IcingaCheckHttpJsonResponseChecks.psm1
  provider/httpJson/Get-IcingaHttpResponse.psm1
  provider/httpJson/Get-ValueFromJsonObject.psm1
Labels: enhancement, cla/signed
